# Generated by Django 5.0.7 on 2026-05-28 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('offer', 'Публичная оферта'), ('privacy', 'Политика конфиденциальности'), ('refund', 'Политика возвратов'), ('personal_data', 'Согласие на обработку ПДн')], max_length=30, unique=True, verbose_name='Тип документа')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Юридический документ',
                'verbose_name_plural': 'Юридические документы',
                'ordering': ('doc_type',),
            },
        ),
        migrations.CreateModel(
            name='PremiumFeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True, verbose_name='Ключ функции')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Премиум функция')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Флаг премиум функции',
                'verbose_name_plural': 'Флаги премиум функций',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='ru', max_length=10, verbose_name='Язык')),
                ('show_overdue', models.BooleanField(default=True, verbose_name='Показывать просрочено')),
                ('show_today', models.BooleanField(default=True, verbose_name='Показывать сегодня')),
                ('show_tomorrow', models.BooleanField(default=True, verbose_name='Показывать завтра')),
                ('show_later', models.BooleanField(default=True, verbose_name='Показывать позже')),
                ('show_no_deadline', models.BooleanField(default=True, verbose_name='Показывать без срока')),
                ('show_completed', models.BooleanField(default=True, verbose_name='Показывать выполнено')),
                ('bottom_tabs', models.JSONField(blank=True, default=list, help_text='Порядок вкладок в нижнем меню.', verbose_name='Вкладки нижнего меню')),
                ('notification_sound', models.CharField(default='default', max_length=120, verbose_name='Звук уведомления')),
                ('completion_sound', models.CharField(default='default', max_length=120, verbose_name='Звук завершения')),
                ('vibration_enabled', models.BooleanField(default=True, verbose_name='Вибрация')),
                ('is_premium', models.BooleanField(default=False, verbose_name='Премиум')),
                ('premium_activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата активации премиум')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки приложения',
                'verbose_name_plural': 'Настройки приложения',
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='help_requests/', verbose_name='Скриншот')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос в поддержку',
                'verbose_name_plural': 'Запросы в поддержку',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PomodoroSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Длительность таймера')),
                ('show_on_lock_screen', models.BooleanField(default=True, verbose_name='Показывать на экране блокировки')),
                ('timer_end_sound', models.CharField(default='default', max_length=120, verbose_name='Звук завершения таймера')),
                ('work_sound', models.CharField(default='none', max_length=120, verbose_name='Фоновая мелодия')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки помодоро',
                'verbose_name_plural': 'Настройки помодоро',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('reminder_at', models.DateTimeField(blank=True, null=True, verbose_name='Напоминание')),
                ('repeat_unit', models.CharField(choices=[('none', 'Без повтора'), ('day', 'День'), ('week', 'Неделя'), ('month', 'Месяц'), ('year', 'Год')], default='none', max_length=10, verbose_name='Единица повтора')),
                ('repeat_interval', models.PositiveIntegerField(default=1, verbose_name='Интервал повтора')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критичный')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('matrix_block', models.CharField(choices=[('urgent_important', 'Срочно и важно'), ('not_urgent_important', 'Не срочно и важно'), ('urgent_not_important', 'Срочно и не важно'), ('not_urgent_not_important', 'Не срочно и не важно')], default='not_urgent_important', max_length=30, verbose_name='Блок матрицы Эйзенхауэра')),
                ('image', models.ImageField(blank=True, null=True, upload_to='task_images/', verbose_name='Изображение')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Выполнено в')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ('is_completed', 'due_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Длительность')),
                ('state', models.CharField(choices=[('idle', 'Ожидание'), ('running', 'Запущен'), ('paused', 'На паузе'), ('stopped', 'Остановлен'), ('completed', 'Завершен')], default='idle', max_length=20, verbose_name='Состояние')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Старт')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pomodoro_sessions', to='planner.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Сессия помодоро',
                'verbose_name_plural': 'Сессии помодоро',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MatrixBlockSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(choices=[('urgent_important', 'Срочно и важно'), ('not_urgent_important', 'Не срочно и важно'), ('urgent_not_important', 'Срочно и не важно'), ('not_urgent_not_important', 'Не срочно и не важно')], max_length=30, verbose_name='Блок')),
                ('title', models.CharField(max_length=100, verbose_name='Название блока')),
                ('allowed_priorities', models.JSONField(blank=True, default=list, verbose_name='Разрешенные приоритеты')),
                ('date_filter', models.CharField(blank=True, default='', max_length=30, verbose_name='Фильтр по дате')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrix_block_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройка блока Эйзенхауэра',
                'verbose_name_plural': 'Настройки блоков Эйзенхауэра',
                'unique_together': {('user', 'block')},
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'due_at'], name='planner_tas_user_id_a7962c_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'is_completed'], name='planner_tas_user_id_b25b11_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'matrix_block'], name='planner_tas_user_id_d627d1_idx'),
        ),
    ]
