# Generated by Django 6.0.4 on 2026-06-02 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_sound_foreign_keys'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sound',
            options={'ordering': ('category', 'sort_order', 'key'), 'verbose_name': 'Звук', 'verbose_name_plural': 'Аудио — все звуки'},
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='completion_sound',
            field=models.ForeignKey(limit_choices_to={'category': 'completion', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='planner.sound', verbose_name='Звук завершения'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='notification_sound',
            field=models.ForeignKey(limit_choices_to={'category': 'notification', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='planner.sound', verbose_name='Звук уведомления'),
        ),
        migrations.AlterField(
            model_name='pomodorosettings',
            name='timer_end_sound',
            field=models.ForeignKey(limit_choices_to={'category': 'timer_end', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='planner.sound', verbose_name='Звук завершения таймера'),
        ),
        migrations.AlterField(
            model_name='pomodorosettings',
            name='work_sound',
            field=models.ForeignKey(limit_choices_to={'category': 'work_background', 'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='planner.sound', verbose_name='Фоновая мелодия'),
        ),
    ]
