# Generated by Django 5.0.7 on 2026-07-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_move_pomodoro_to_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Премиум действует до'),
        ),
    ]
