# Generated by Django 5.0.7 on 2026-07-21 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_billing_and_premium_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_attachments/', verbose_name='Файл')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя файла')),
                ('content_type', models.CharField(blank=True, default='', max_length=120, verbose_name='MIME')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='Размер (байт)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Вложение задачи',
                'verbose_name_plural': '1b. Вложения задач',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='appsettings',
            name='timezone',
            field=models.CharField(default='Europe/Moscow', help_text='Например Europe/Moscow, Asia/Tashkent. Влияет на группы и календарь.', max_length=64, verbose_name='Часовой пояс (IANA)'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_all_day',
            field=models.BooleanField(default=False, help_text='True = задача с датой, но без конкретного времени (верхний блок календаря).', verbose_name='Весь день (дата без времени)'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_occurrences', to='planner.task', verbose_name='Предыдущее вхождение'),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_delivered_at',
            field=models.DateTimeField(blank=True, help_text='Когда клиент подтвердил показ уведомления.', null=True, verbose_name='Напоминание доставлено'),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_offset_minutes',
            field=models.IntegerField(blank=True, help_text='0 = в момент срока, 15 = за 15 минут. Клиент может сам считать reminder_at.', null=True, verbose_name='Смещение напоминания (мин до срока)'),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_until',
            field=models.DateField(blank=True, null=True, verbose_name='Повторять до'),
        ),
        migrations.AddField(
            model_name='task',
            name='series_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Общий идентификатор всех вхождений повторяющейся задачи.', null=True, verbose_name='ID серии повторов'),
        ),
        migrations.AlterField(
            model_name='matrixblocksetting',
            name='date_filter',
            field=models.CharField(blank=True, default='', help_text='any | overdue | today | tomorrow | later | no_deadline | with_deadline', max_length=30, verbose_name='Фильтр по дате'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'reminder_at'], name='planner_tas_user_id_21c549_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'series_id'], name='planner_tas_user_id_bc5d8b_idx'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='planner.task', verbose_name='Задача'),
        ),
    ]
