# Generated by Django 5.0.7 on 2026-07-21 07:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_backlog_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Вопрос FAQ',
                'verbose_name_plural': '4a. FAQ',
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True, verbose_name='FCM token')),
                ('device_id', models.CharField(max_length=255, verbose_name='ID устройства')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Название устройства')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=16, verbose_name='Платформа')),
                ('app_version', models.CharField(blank=True, default='', max_length=50, verbose_name='Версия приложения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Устройство FCM',
                'verbose_name_plural': '3b. Устройства FCM',
                'ordering': ('-last_seen_at',),
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='pending', max_length=16, verbose_name='Статус')),
                ('message_id', models.CharField(blank=True, default='', max_length=255, verbose_name='FCM message ID')),
                ('error', models.TextField(blank=True, default='', verbose_name='Ошибка')),
                ('attempted_at', models.DateTimeField(blank=True, null=True, verbose_name='Попытка отправки')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to='planner.fcmdevice', verbose_name='Устройство')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to='planner.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Доставка уведомления',
                'verbose_name_plural': '3c. Доставка уведомлений',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='fcmdevice',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='unique_user_fcm_device'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('task', 'device'), name='unique_task_device_notification'),
        ),
    ]
