# Generated by Django 5.0.7 on 2026-07-21 07:12

from django.db import migrations, models


def copy_legacy_date_filter(apps, schema_editor):
    """Переносит старый одиночный date_filter в новый список date_filters."""
    MatrixBlockSetting = apps.get_model("planner", "MatrixBlockSetting")
    for item in MatrixBlockSetting.objects.exclude(date_filter=""):
        if not item.date_filters:
            item.date_filters = [item.date_filter]
            item.save(update_fields=["date_filters"])


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_seed_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixblocksetting',
            name='date_filters',
            field=models.JSONField(blank=True, default=list, help_text='Список: overdue, today, tomorrow, later, no_deadline, with_deadline.', verbose_name='Фильтры по дате'),
        ),
        migrations.RunPython(copy_legacy_date_filter, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='matrixblocksetting',
            name='date_filter',
            field=models.CharField(blank=True, default='', help_text='Legacy single value; use date_filters for multiple values.', max_length=30, verbose_name='Фильтр по дате'),
        ),
    ]
