# Generated by Django 5.0.7 on 2026-07-23 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_matrix_multiple_date_filters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('task_reminder', 'Напоминание о задаче'), ('system', 'Системное'), ('premium', 'Премиум')], default='task_reminder', max_length=32, verbose_name='Тип')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, default='', verbose_name='Текст')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Данные')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано в')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_notifications', to='planner.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Уведомление пользователя',
                'verbose_name_plural': '3d. Уведомления пользователя',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='planner_use_user_id_523240_idx'), models.Index(fields=['user', '-created_at'], name='planner_use_user_id_0a2875_idx')],
            },
        ),
    ]
