# Generated by Django 5.2.6 on 2026-04-30 17:41

import apps.accounts.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', apps.accounts.models.CustomUserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='passwordresetrequest',
            new_name='accounts_pa_email_adcef2_idx',
            old_name='accounts_pas_email_0a5c77_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetrequest',
            new_name='accounts_pa_reset_t_65ca4f_idx',
            old_name='accounts_pas_reset_t_1f5f65_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок действия'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='reset_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Токен сброса'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Использован'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]

