# Generated by Django 5.0.7 on 2026-07-11 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True, verbose_name='Код')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('duration_days', models.PositiveIntegerField(help_text='Сколько дней премиума даёт оплата. 0 = бессрочно.', verbose_name='Длительность (дней)')),
                ('promo_days', models.PositiveIntegerField(default=0, help_text='Бесплатный период на нашей стороне (Robokassa промо не даёт).', verbose_name='Промо-период (дней)')),
                ('is_recurring', models.BooleanField(default=True, help_text='Автосписание через Robokassa Recurring API.', verbose_name='Рекуррентный')),
                ('receipt_name', models.CharField(help_text='Номенклатура для фискализации Robokassa.', max_length=128, verbose_name='Название в чеке')),
                ('vat', models.CharField(default='none', help_text='none | vat0 | vat10 | vat20 | vat110 | vat120', max_length=16, verbose_name='НДС')),
                ('payment_object', models.CharField(default='service', max_length=32, verbose_name='Предмет расчёта')),
                ('payment_method', models.CharField(default='full_payment', max_length=32, verbose_name='Способ расчёта')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': '1. Тарифы',
                'ordering': ('sort_order', 'price'),
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('none', 'Нет'), ('trial', 'Промо-период'), ('active', 'Активна'), ('past_due', 'Просрочена оплата'), ('cancelled', 'Отменена'), ('expired', 'Истекла')], default='none', max_length=20, verbose_name='Статус')),
                ('promo_until', models.DateTimeField(blank=True, null=True, verbose_name='Промо до')),
                ('premium_until', models.DateTimeField(blank=True, null=True, verbose_name='Премиум до')),
                ('recurring_enabled', models.BooleanField(default=False, verbose_name='Автосписание включено')),
                ('parent_invoice_id', models.PositiveBigIntegerField(blank=True, help_text='Нужен для дочерних recurring-списаний.', null=True, verbose_name='InvId материнского платежа')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': '2. Подписки',
            },
        ),
        migrations.CreateModel(
            name='RecurringConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_version', models.CharField(blank=True, default='', max_length=64, verbose_name='Версия оферты')),
                ('agreed', models.BooleanField(default=True, verbose_name='Согласие')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуально')),
                ('agreed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата согласия')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозвано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_consents', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consents', to='billing.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Согласие на автосписание',
                'verbose_name_plural': '3. Согласия на автосписание',
                'ordering': ('-agreed_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.PositiveBigIntegerField(unique=True, verbose_name='InvId')),
                ('previous_invoice_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='PreviousInvoiceID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('kind', models.CharField(choices=[('initial', 'Первый / материнский'), ('recurring', 'Дочерний (recurring)'), ('one_time', 'Разовый')], default='initial', max_length=20, verbose_name='Тип')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка'), ('cancelled', 'Отменён')], default='pending', max_length=20, verbose_name='Статус')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Описание')),
                ('checkout_url', models.TextField(blank=True, default='', verbose_name='Checkout URL')),
                ('raw_result', models.JSONField(blank=True, default=dict, verbose_name='Ответ Robokassa')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': '4. Платежи',
                'ordering': ('-created_at',),
            },
        ),
    ]
