# Generated by Django 5.0.7 on 2026-07-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_tariffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='channel',
            field=models.CharField(choices=[('web', 'Web / Desktop'), ('mobile_sdk', 'Mobile SDK')], default='web', max_length=20, verbose_name='Канал'),
        ),
    ]
